---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 35064.
--- DateTime: 2023/11/18 15:57
---
local key = KEYS[1];--锁的key
local threadId = ARGV[1];--线程Id
local releaseTime = ARGV[2];--锁的自动释放时间
if(redis.call('exists',key) == 0) then
    --不存在，获取锁
    redis.call('hset',key,threadId,'1');
    -- 设置过期时间
    redis.call('expire',key,releaseTime);
    return 1;
end;
--锁已经存在，判断threadId是否是自己的
if(redis.call('hexists',key,threadId) == 1) then
    -- 是，则重入次数加一
    redis.call('hincrby',key,threadId,1);
    -- 同时，更新过期时间
    redis.call('expire',key,releaseTime);
    return 1;
end;
return 0;